name: camera_geo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  permission_handler: 10.2.0
  path_provider: 2.0.12
  image_picker: 0.8.6+1
  geolocator: 9.0.2
  geocoding: 2.0.5
  lottie: 2.2.0
  gallery_saver: ^2.3.2
  widgets_to_image: 0.0.2
  open_filex: 4.3.2
  google_mobile_ads: 2.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.12.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'
  min_sdk_android: 21
